// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/tinyurl/v1/tinyurl.proto

package tinyurlv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LongUrl       string                 `protobuf:"bytes,1,opt,name=long_url,proto3" json:"long_url,omitempty"`
	ShortCode     string                 `protobuf:"bytes,2,opt,name=short_code,proto3" json:"short_code,omitempty"` // Optional custom alias
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenRequest) Reset() {
	*x = ShortenRequest{}
	mi := &file_proto_tinyurl_v1_tinyurl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenRequest) ProtoMessage() {}

func (x *ShortenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tinyurl_v1_tinyurl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenRequest.ProtoReflect.Descriptor instead.
func (*ShortenRequest) Descriptor() ([]byte, []int) {
	return file_proto_tinyurl_v1_tinyurl_proto_rawDescGZIP(), []int{0}
}

func (x *ShortenRequest) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

func (x *ShortenRequest) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

type ShortenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,proto3" json:"short_url,omitempty"`
	LongUrl       string                 `protobuf:"bytes,2,opt,name=long_url,proto3" json:"long_url,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ElapsedTime   string                 `protobuf:"bytes,4,opt,name=elapsed_time,proto3" json:"elapsed_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenResponse) Reset() {
	*x = ShortenResponse{}
	mi := &file_proto_tinyurl_v1_tinyurl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenResponse) ProtoMessage() {}

func (x *ShortenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tinyurl_v1_tinyurl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenResponse.ProtoReflect.Descriptor instead.
func (*ShortenResponse) Descriptor() ([]byte, []int) {
	return file_proto_tinyurl_v1_tinyurl_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *ShortenResponse) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

func (x *ShortenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ShortenResponse) GetElapsedTime() string {
	if x != nil {
		return x.ElapsedTime
	}
	return ""
}

type GetOriginalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,proto3" json:"short_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOriginalRequest) Reset() {
	*x = GetOriginalRequest{}
	mi := &file_proto_tinyurl_v1_tinyurl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOriginalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOriginalRequest) ProtoMessage() {}

func (x *GetOriginalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tinyurl_v1_tinyurl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOriginalRequest.ProtoReflect.Descriptor instead.
func (*GetOriginalRequest) Descriptor() ([]byte, []int) {
	return file_proto_tinyurl_v1_tinyurl_proto_rawDescGZIP(), []int{2}
}

func (x *GetOriginalRequest) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

type GetOriginalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LongUrl       string                 `protobuf:"bytes,1,opt,name=long_url,proto3" json:"long_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOriginalResponse) Reset() {
	*x = GetOriginalResponse{}
	mi := &file_proto_tinyurl_v1_tinyurl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOriginalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOriginalResponse) ProtoMessage() {}

func (x *GetOriginalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tinyurl_v1_tinyurl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOriginalResponse.ProtoReflect.Descriptor instead.
func (*GetOriginalResponse) Descriptor() ([]byte, []int) {
	return file_proto_tinyurl_v1_tinyurl_proto_rawDescGZIP(), []int{3}
}

func (x *GetOriginalResponse) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

var File_proto_tinyurl_v1_tinyurl_proto protoreflect.FileDescriptor

const file_proto_tinyurl_v1_tinyurl_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/tinyurl/v1/tinyurl.proto\x12\n" +
	"tinyurl.v1\x1a\x1cgoogle/api/annotations.proto\"L\n" +
	"\x0eShortenRequest\x12\x1a\n" +
	"\blong_url\x18\x01 \x01(\tR\blong_url\x12\x1e\n" +
	"\n" +
	"short_code\x18\x02 \x01(\tR\n" +
	"short_code\"\x89\x01\n" +
	"\x0fShortenResponse\x12\x1c\n" +
	"\tshort_url\x18\x01 \x01(\tR\tshort_url\x12\x1a\n" +
	"\blong_url\x18\x02 \x01(\tR\blong_url\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\"\n" +
	"\felapsed_time\x18\x04 \x01(\tR\felapsed_time\"4\n" +
	"\x12GetOriginalRequest\x12\x1e\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\n" +
	"short_code\"1\n" +
	"\x13GetOriginalResponse\x12\x1a\n" +
	"\blong_url\x18\x01 \x01(\tR\blong_url2\xd0\x01\n" +
	"\aTinyURL\x12W\n" +
	"\aShorten\x12\x1a.tinyurl.v1.ShortenRequest\x1a\x1b.tinyurl.v1.ShortenResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/tinyurl\x12l\n" +
	"\vGetOriginal\x12\x1e.tinyurl.v1.GetOriginalRequest\x1a\x1f.tinyurl.v1.GetOriginalResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/url/{short_code}BEZCgithub.com/eldivategar/simple-tinyurl-go/proto/tinyurl/v1;tinyurlv1b\x06proto3"

var (
	file_proto_tinyurl_v1_tinyurl_proto_rawDescOnce sync.Once
	file_proto_tinyurl_v1_tinyurl_proto_rawDescData []byte
)

func file_proto_tinyurl_v1_tinyurl_proto_rawDescGZIP() []byte {
	file_proto_tinyurl_v1_tinyurl_proto_rawDescOnce.Do(func() {
		file_proto_tinyurl_v1_tinyurl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tinyurl_v1_tinyurl_proto_rawDesc), len(file_proto_tinyurl_v1_tinyurl_proto_rawDesc)))
	})
	return file_proto_tinyurl_v1_tinyurl_proto_rawDescData
}

var file_proto_tinyurl_v1_tinyurl_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_tinyurl_v1_tinyurl_proto_goTypes = []any{
	(*ShortenRequest)(nil),      // 0: tinyurl.v1.ShortenRequest
	(*ShortenResponse)(nil),     // 1: tinyurl.v1.ShortenResponse
	(*GetOriginalRequest)(nil),  // 2: tinyurl.v1.GetOriginalRequest
	(*GetOriginalResponse)(nil), // 3: tinyurl.v1.GetOriginalResponse
}
var file_proto_tinyurl_v1_tinyurl_proto_depIdxs = []int32{
	0, // 0: tinyurl.v1.TinyURL.Shorten:input_type -> tinyurl.v1.ShortenRequest
	2, // 1: tinyurl.v1.TinyURL.GetOriginal:input_type -> tinyurl.v1.GetOriginalRequest
	1, // 2: tinyurl.v1.TinyURL.Shorten:output_type -> tinyurl.v1.ShortenResponse
	3, // 3: tinyurl.v1.TinyURL.GetOriginal:output_type -> tinyurl.v1.GetOriginalResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_tinyurl_v1_tinyurl_proto_init() }
func file_proto_tinyurl_v1_tinyurl_proto_init() {
	if File_proto_tinyurl_v1_tinyurl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tinyurl_v1_tinyurl_proto_rawDesc), len(file_proto_tinyurl_v1_tinyurl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tinyurl_v1_tinyurl_proto_goTypes,
		DependencyIndexes: file_proto_tinyurl_v1_tinyurl_proto_depIdxs,
		MessageInfos:      file_proto_tinyurl_v1_tinyurl_proto_msgTypes,
	}.Build()
	File_proto_tinyurl_v1_tinyurl_proto = out.File
	file_proto_tinyurl_v1_tinyurl_proto_goTypes = nil
	file_proto_tinyurl_v1_tinyurl_proto_depIdxs = nil
}
