// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: proto/tinyurl/v1/tinyurl.proto

package tinyurlv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TinyURL_Shorten_FullMethodName     = "/tinyurl.v1.TinyURL/Shorten"
	TinyURL_GetOriginal_FullMethodName = "/tinyurl.v1.TinyURL/GetOriginal"
)

// TinyURLClient is the client API for TinyURL service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TinyURLClient interface {
	// Shorten accepts a long URL and returns a short URL/code.
	Shorten(ctx context.Context, in *ShortenRequest, opts ...grpc.CallOption) (*ShortenResponse, error)
	// GetOriginal retrieves the original URL for a given short code.
	// This is primarily for internal use by the Redirect handler,
	// but exposed via API for completeness.
	GetOriginal(ctx context.Context, in *GetOriginalRequest, opts ...grpc.CallOption) (*GetOriginalResponse, error)
}

type tinyURLClient struct {
	cc grpc.ClientConnInterface
}

func NewTinyURLClient(cc grpc.ClientConnInterface) TinyURLClient {
	return &tinyURLClient{cc}
}

func (c *tinyURLClient) Shorten(ctx context.Context, in *ShortenRequest, opts ...grpc.CallOption) (*ShortenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShortenResponse)
	err := c.cc.Invoke(ctx, TinyURL_Shorten_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tinyURLClient) GetOriginal(ctx context.Context, in *GetOriginalRequest, opts ...grpc.CallOption) (*GetOriginalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOriginalResponse)
	err := c.cc.Invoke(ctx, TinyURL_GetOriginal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TinyURLServer is the server API for TinyURL service.
// All implementations must embed UnimplementedTinyURLServer
// for forward compatibility.
type TinyURLServer interface {
	// Shorten accepts a long URL and returns a short URL/code.
	Shorten(context.Context, *ShortenRequest) (*ShortenResponse, error)
	// GetOriginal retrieves the original URL for a given short code.
	// This is primarily for internal use by the Redirect handler,
	// but exposed via API for completeness.
	GetOriginal(context.Context, *GetOriginalRequest) (*GetOriginalResponse, error)
	mustEmbedUnimplementedTinyURLServer()
}

// UnimplementedTinyURLServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTinyURLServer struct{}

func (UnimplementedTinyURLServer) Shorten(context.Context, *ShortenRequest) (*ShortenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Shorten not implemented")
}
func (UnimplementedTinyURLServer) GetOriginal(context.Context, *GetOriginalRequest) (*GetOriginalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOriginal not implemented")
}
func (UnimplementedTinyURLServer) mustEmbedUnimplementedTinyURLServer() {}
func (UnimplementedTinyURLServer) testEmbeddedByValue()                 {}

// UnsafeTinyURLServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TinyURLServer will
// result in compilation errors.
type UnsafeTinyURLServer interface {
	mustEmbedUnimplementedTinyURLServer()
}

func RegisterTinyURLServer(s grpc.ServiceRegistrar, srv TinyURLServer) {
	// If the following call panics, it indicates UnimplementedTinyURLServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TinyURL_ServiceDesc, srv)
}

func _TinyURL_Shorten_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TinyURLServer).Shorten(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TinyURL_Shorten_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TinyURLServer).Shorten(ctx, req.(*ShortenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TinyURL_GetOriginal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOriginalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TinyURLServer).GetOriginal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TinyURL_GetOriginal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TinyURLServer).GetOriginal(ctx, req.(*GetOriginalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TinyURL_ServiceDesc is the grpc.ServiceDesc for TinyURL service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TinyURL_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tinyurl.v1.TinyURL",
	HandlerType: (*TinyURLServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Shorten",
			Handler:    _TinyURL_Shorten_Handler,
		},
		{
			MethodName: "GetOriginal",
			Handler:    _TinyURL_GetOriginal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tinyurl/v1/tinyurl.proto",
}
